/**
 * Generated Tracker Configuration
 * 
 * Structure returned by AI for custom tracker configuration.
 * This enables contextual UI for any user-created tracker.
 */

/**
 * Intensity scale type determines color mapping:
 * - 'high_bad': High values are concerning (pain, blood pressure, anxiety)
 * - 'low_bad': Low values are concerning (mood, energy, oxygen levels)
 * - 'neutral': Scale is measurement without good/bad (exercise intensity)
 */
export type IntensityScale = 'low_bad' | 'high_bad' | 'neutral';

/**
 * Structure generated by AI for custom tracker configuration
 */
export interface GeneratedTrackerConfig {
  // Form labels
  intensityLabel: string;
  intensityMinLabel: string;
  intensityMaxLabel: string;
  locationLabel: string;
  locationPlaceholder: string;
  triggersLabel: string;
  notesLabel: string;
  notesPlaceholder: string;
  
  // Button labels
  addButtonLabel: string;
  formTitle: string;
  
  // Empty state content
  emptyStateTitle: string;
  emptyStateDescription: string;
  emptyStateBullets: string[];
  
  // Card/detail labels
  entryTitle: string;
  deleteConfirmMessage: string;
  
  // Options - AI generates contextually relevant options
  locations: { value: string; label: string }[];
  triggers: string[];
  
  // Suggested hashtags for quick-add (without # symbol)
  suggestedHashtags: string[];
  
  // Intensity scale interpretation
  intensityScale: IntensityScale;
}

/**
 * Result from dictionary lookup
 */
export interface DictionaryResult {
  word: string;
  definition: string;
  partOfSpeech?: string;
  examples: string[];
  synonyms: string[];
}

/**
 * Dictionary cache entry (matches database schema)
 */
export interface DictionaryCacheEntry {
  word: string;
  definition: string;
  part_of_speech?: string;
  examples?: string[];
  synonyms?: string[];
  fetched_at?: string;
}
